[versions]
kotlin = "1.9.23"
openrndr = "0.4.5-SNAPSHOT"
orx = "0.4.5-SNAPSHOT"

[libraries]
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

openrndr-application = { group = "org.openrndr", name = "openrndr-application", version.ref = "openrndr" }
openrndr-dds = { group = "org.openrndr", name = "openrndr-dds", version.ref = "openrndr" }
openrndr-draw = { group = "org.openrndr", name = "openrndr-draw", version.ref = "openrndr" }
openrndr-webgl = { group = "org.openrndr", name = "openrndr-webgl", version.ref = "openrndr" }

orx-svg = { group = "org.openrndr.extra", name = "orx-svg", version.ref = "openrndr" }
orx-composition = { group = "org.openrndr.extra", name = "orx-composition", version.ref = "openrndr" }
orx-shapes = { group = "org.openrndr.extra", name = "orx-shapes", version.ref = "openrndr" }

[plugins]
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }